### ISSUE TITLE
Suggestion: use `neovim-plugin`, not `nvim-plugin` and `neovim-plugins`

### ISSUE THREAD

**Issue by andmis** [mnowotnik/noteflow.nvim#7]
In your repo tags, you have `nvim-plugin` and `neovim-plugins`:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/5308024/169598564-b24db628-e7c9-4ee7-8a26-0b5251876451.png">

Both of those tags are much less popular than `neovim-plugin` (~20 and ~180 repos, vs. ~800 repos).

**Comment by mnowotnik** [comment]
You're right. I added the neovim-plugin tag.
